name: build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.2
          actions-cache-folder: emsdk-cache
      - uses: actions/setup-node@v2
        with:
          node-version: 17
      - run: corepack pnpm install
      - name: check code style
        run: |
          sudo apt install --no-install-recommends clang-format-11
          make lint
          corepack pnpm run lint
          git diff --exit-code
      - name: build project
        run: |
          make
          corepack pnpm run build
      - run: corepack pnpm test
      - name: prepare deploy
        run: |
          tar xzf $(corepack pnpm pack .)
      - uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: build
          build_dir: ./package/
          commit_message: ${{ github.sha }} ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.ref_name == 'main' && github.event_name == 'push' }}
