name: build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: mymindstorm/setup-emsdk@v8
        with:
          version: 2.0.18
          actions-cache-folder: emsdk-cache
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install
      - name: check code style
        run: |
          sudo apt install --no-install-recommends clang-format-8
          make lint
          npm run lint
          [[ $(git status --porcelain | tee >(cat 1>&2) | wc -l) -eq 0 ]]
      - name: build project
        run: |
          make
          npm run build
      - run: npm test
      - name: prepare deploy
        run: |
          tar xzf $(npm pack .)
      - uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: build
          build_dir: ./package/
          commit_message: ${{ github.sha }} ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.event_name == 'push' }}
